package com.CodeMasters.blackboxTesting;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class EditProfileTestCodeMastersTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void editProfileTestCodeMasters() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(775, 468));
		driver.findElement(By.name("id")).click();
		driver.findElement(By.name("id")).sendKeys("001");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("Parham");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector("th:nth-child(2) > .list-group-item")).click();
		driver.findElement(By.name("name")).click();
		driver.findElement(By.name("name")).clear();
		driver.findElement(By.name("name")).click();
		driver.findElement(By.name("name")).sendKeys("Parham");
		driver.findElement(By.cssSelector("#server > .form-group")).click();
		driver.findElement(By.name("phone")).click();
		driver.findElement(By.name("phone")).clear();
		driver.findElement(By.name("phone")).click();
		driver.findElement(By.name("phone")).sendKeys("12345678");
		driver.findElement(By.cssSelector(".btn-success")).click();
		driver.findElement(By.linkText("Return to Home Page")).click();
	}
}
