package com.CodeMasters.blackboxTesting;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class EditTableTestCodeMastersTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:/temp/chromedriver.exe");

		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void editTableTestCodeMasters() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(775, 468));
		driver.findElement(By.name("id")).click();
		driver.findElement(By.name("id")).sendKeys("001");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("Rahim");
		driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector("th:nth-child(1) > .list-group-item")).click();
		driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3) > a")).click();
		driver.findElement(By.name("ReservationID")).click();
		driver.findElement(By.name("ReservationID")).sendKeys("000");
		driver.findElement(By.name("serverID")).click();
		{
			WebElement dropdown = driver.findElement(By.name("serverID"));
			dropdown.findElement(By.xpath("//option[. = 'Parham']")).click();
		}
		driver.findElement(By.name("serverID")).click();
		driver.findElement(By.name("billID")).click();
		driver.findElement(By.name("billID")).sendKeys("000000");
		driver.findElement(By.name("time")).click();
		driver.findElement(By.name("time")).click();
		driver.findElement(By.name("time")).sendKeys("11:29");
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.name("date")).click();
		driver.findElement(By.name("date")).sendKeys("2020-12-02");
		driver.findElement(By.name("isAvailable")).click();
		{
			WebElement dropdown = driver.findElement(By.name("isAvailable"));
			dropdown.findElement(By.xpath("//option[. = 'Unavailable']")).click();
		}
		driver.findElement(By.name("isAvailable")).click();
		driver.findElement(By.cssSelector(".form-group > .btn")).click();
	}
}
